apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: insecure-port
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
